# Generated by Django 5.0.2 on 2024-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todos_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='doing',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
