# Generated by Django 5.0 on 2024-01-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок записи"),
                ),
                ("description", models.TextField(verbose_name="Текст записи")),
                ("author", models.CharField(max_length=100, verbose_name="Имя автора")),
                ("date", models.DateField(verbose_name="Дата публикации")),
                (
                    "img",
                    models.ImageField(upload_to="image/%Y", verbose_name="Изображение"),
                ),
            ],
            options={"verbose_name": "Запись", "verbose_name_plural": "Записи",},
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "text_comments",
                    models.TextField(max_length=2000, verbose_name="Текст комментарии"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.post",
                        verbose_name="Публикация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарий",
            },
        ),
    ]
